[supervisord]
nodaemon=true
user=app
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm
autorestart=true

[program:symfony-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/app/bin/console messenger:consume async --time-limit=3600
autostart=true
autorestart=true
user=app
numprocs=2
